@HabitTrackerWebApp_HostAddress = http://localhost:5189

GET {{HabitTrackerWebApp_HostAddress}}/api/habits/
Accept: application/json

###

GET {{HabitTrackerWebApp_HostAddress}}/api/habits/3
Accept: application/json

###

POST {{HabitTrackerWebApp_HostAddress}}/api/habits/
Content-Type: application/json

{
    "name": "NewHabit"
}

###

POST {{HabitTrackerWebApp_HostAddress}}/api/habits/3/mark-completed
Content-Type: application/json

{
    "date": "2025-04-18"
}

###

PUT {{HabitTrackerWebApp_HostAddress}}/api/habits/3
Content-Type: application/json

{
    "id": 3,
    "name": "NewHabitName"
}

###

DELETE {{HabitTrackerWebApp_HostAddress}}/api/habits/3

###