@HabitTrackerWebApp_HostAddress = http://localhost:5189

GET {{HabitTrackerWebApp_HostAddress}}/habits/
Accept: application/json

###

GET {{HabitTrackerWebApp_HostAddress}}/habits/Test
Accept: application/json

###

POST {{HabitTrackerWebApp_HostAddress}}/habits/
Content-Type: application/json

{
    "name": "YoYoyy"
}

###